### PR TITLE
[ruby31-v1.14.x] LOG-3314:Upgrade fluent-plugin-kafka to 0.19.0

### PR DESCRIPTION
**Pull request by vparfonov**
### Description

/cc 
/assign 

/cherry-pick 

### Links

- Depending on PR(s):
- Bugzilla:
- Github issue:
- JIRA: https://issues.redhat.com/browse/LOG-3314
- Enhancement proposal:

### CODE REVIEW

**Comment by jcantrill** [comment]
This does not look like the correct fix.  I would set the version needed here https://github.com/ViaQ/logging-fluentd/blob/ruby31-v1.14.x/fluentd/Gemfile#L9 and update the lock accordingly.  We now rely upon caching so I would not expect any other changes then this file and its lock

**Comment by vparfonov** [comment]
> This does not look like the correct fix. I would set the version needed here [`ruby31-v1.14.x`/fluentd/Gemfile#L9](https://github.com/ViaQ/logging-fluentd/blob/ruby31-v1.14.x/fluentd/Gemfile?rgh-link-date=2023-05-25T15%3A37%3A20Z#L9) and update the lock accordingly. We now rely upon caching so I would not expect any other changes then this file and its lock

Got it. Fixed

**Comment by jcantrill** [comment]
/hold

@vparfonov bundle install the Gemfile will also update the lock file so this commit should only contain:
* Gemfile
* Gemfile.lock with minimal changes

**Comment by vparfonov** [comment]
> /hold
> 
> @vparfonov bundle install the Gemfile will also update the lock file so this commit should only contain:
> 
> * Gemfile
> * Gemfile.lock with minimal changes

Yes, but i got some strange changes with `remote_syslog_sender (= 1.2.1)`, i didn't understand how it related so didn't commit it.
https://github.com/ViaQ/logging-fluentd/pull/88/files#diff-019b5df7363d41bf4c25366ac4e32cbb2865753d3ecbec47537f556d32538bf2L17

**Pull request merged**
