### PR TITLE
LOG-2099: Add sequence number to log messages to fix entry order

### PR DESCRIPTION
**Pull request by jcantrill**
### Description
This PR:
* Updates the viaq data model to add a sequence number to address log entries where timestamp does not provide great enough resolution

### Links
* https://issues.redhat.com/browse/LOG-2099

cc @alanconway @vimalk78

### CODE REVIEW

**Comment by jcantrill** [comment]
@alanconway thoughts here?  This is inline with what we discussed for this issue?

**Review by alanconway — APPROVED** [review]
/lgtm

**Pull request merged**
