### PR TITLE
Update fluent-plugin-kubernetes_metadata to fix the testapiadapter

### PR DESCRIPTION
**Pull request by jcantrill**
### Description
This PR:
* Updates the kubernetes meta_data plugin to pull in a fix for the TestAPIAdapter https://issues.redhat.com/browse/LOG-2289

### Links
* v1.7.4 backport of #9

### CODE REVIEW

**Review by alanconway — APPROVED** [review]
/lgtm

**Comment by jcantrill** [comment]
Force merge to unblock other PRs

**Pull request merged**
